defaults:
  - augmentation@datasets.train_augs:
      - horizontalflip
      - verticalflip
      - normalize
  - augmentation@datasets.valid_augs:
      - normalize

datasets:
  _target_: src.dataloader.base_dataset.BaseDataLoader
  data_root: ${data_dir}
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  fold_num: 0
  seed: ${seed}


