# @package _global_

defaults:
  - override /dataloader: baseloader
  - override /framework: basemodel
  - override /logger: none
  - override /hydra: default
  - override /callbacks: none
  - override /trainer: default

model_name: densenet161
num_linear: 1
lr: 0.00005

batch_size: 16
num_workers: 0

seed: 255
run_name: ${model_name}
work_dir: ${hydra:runtime.cwd}

tags:
  - ${model_name}
  - num_linear_${num_linear}

wandb_api_key:  ${oc.env:wandb_api_key}
data_dir: ${oc.env:data_dir}