ModelCheckpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "valid/f1_score"
  mode: "max"
  verbose: False
#  dirpath: ${work_dir}/logs/runs/${run_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  filename: "{epoch:02d}"
  save_top_k: 10