ModelCheckpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "valid/loss"
  mode: "min"
  verbose: False
  dirpath: ${work_dir}/logs/runs/${run_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  filename: "{epoch:02d}"