_target_: src.pl_models.base_pl_module.BasePlModule
model:
  _target_: src.models.pretrained_models.PretrainedModel
  model_name: ${model_name}
  num_layers: ${num_linear}
  dropout_ratio: 0.8
lr: ${lr}
train_loss:
  _target_: torch.nn.CrossEntropyLoss
valid_loss:
  _target_: torch.nn.CrossEntropyLoss
