_target_: src.pl_models.base_pl_module.BasePlModule
model:
  _target_: src.models.pretrained_models.PretrainedModel
  model_name: resnet50
  num_layers: 1
  dropout_ratio: 0.8
lr: 0.0001
train_loss:
  _target_: torch.nn.CrossEntropyLoss
valid_loss:
  _target_: torch.nn.CrossEntropyLoss
